# Generated by Django 4.2 on 2023-08-15 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KakeboWeek",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.IntegerField(default=1)),
                ("year", models.IntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KakeboWeekTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_row", models.JSONField(default=dict)),
                (
                    "type_cost",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "basic necessities"),
                            (1, "optional"),
                            (2, "culture and leisure"),
                            (3, "extras and unexpected"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "kakebo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_kakebo.kakeboweek",
                    ),
                ),
            ],
        ),
    ]
