# Generated by Django 4.2.5 on 2025-02-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_kakebo", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UtilitiesCost",
        ),
        migrations.AlterField(
            model_name="kakeboendofmonthbalance",
            name="answer_1",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="kakeboendofmonthbalance",
            name="answer_2",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="kakeboendofmonthbalance",
            name="answer_3",
            field=models.TextField(blank=True, default=""),
        ),
    ]
